spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_tracker
    username: finance_user
    password: finance_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

app:
  jwt:
    secret: your_super_long_256_bit_secret_key_change_me_1234567890
    expiration-ms: 3600000